version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: stage_user
      POSTGRES_PASSWORD: qwerty789
      POSTGRES_DB: test_db

  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
