name: update_app

on:
  push:
    branches:
      - main

jobs:
  check_ssh_connection:
    runs-on: ubuntu-latest

    steps:
    - name: Check SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: echo "SSH connection successful"

  check_docker:
    needs: check_ssh_connection
    runs-on: ubuntu-latest

    steps:
    - name: Connect to VPS and check Docker installation
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker is not installed on the VPS"
            exit 1
          fi

  deploy:
    needs: check_docker
    runs-on: ubuntu-latest

    steps:
    - name: Connect to VPS and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /var/www/test/flask_test
          git pull
          docker-compose up -d --build
